### ISSUE TITLE
crashes when i use SKSE64

### ISSUE THREAD

**Issue by KopyKatz** [Modorganizer2/modorganizer#167]
# The problem

Skyrim crashes at boot when i use skse64_loader.exe through MO2
# Environment

* Mod Organizer Version that exhibits the issue: 2.1.0.1
* Last Mod Organizer Verison that did not exhibit the issue (if applicable):2.0.8.3
* Desktop OS/version used to run Mod Organizer: Windows 10

**Comment by CptMcSplody** [comment]
Can you run SSE through steam and then skse from sse dir and see if they both work

**Comment by KopyKatz** [comment]
Yes, I can run SKSE outside MO2 and from steam

**Comment by erasmux** [comment]
Please supply a crash dump.

**Comment by KopyKatz** [comment]
Is not MO2 that crash is Skyrim and my crash map is emty.
and only crash if i start skyrim whit skse64 from MO2 when i try start whit skse64 from my Skyrim map it works.
And what is discord channel ? never hear abourt it before.

**Comment by erasmux** [comment]
The discord channel is on the main github page (https://github.com/LePresidente/modorganizer).

Because of technical details, currently, MO will not create a crash dump for injected processes unless the crash is directly inside the usvfs code. Basically this means that in most cases it will not create a crash dump.

Check ["collecting user mode dumps windows"](https://www.google.co.il/search?q=collecting+user+mode+dumps+window) on how to collect a crash dump with WER. I suggest setting DumpType to 1 (which should also be the default so not settings this at all is also good), because full dumps can get very very large.

**Comment by Silarn** [comment]
Unless you are running the exact same mod setup outside of MO, running SKSE outside MO is pretty meaningless. Does it crash with all mods disabled in MO?

This is far more likely to be an outdated SKSE plugin installed within MO. Older versions of MO often did not load SKSE plugins. So in fact this can be an external error caused by the fact that this bug was fixed and the outdated plugins are now loading.

**Comment by erasmux** [comment]
Retest with the usvfs 0.3 beta available on the discord channel (link on main github page). If the problem persists let me know (preferably also on the discord channel).

**Comment by Al12rs** [comment]
I will close this if there is no feedback in the next days

**Comment by rgaston414** [comment]
I’m having this exact same problem. I disable all mods in MO2 and it still crashes when launched through SKSE64 through MO2. I have tried what the OP has. Please help someone

**Comment by CptMcSplody** [comment]
Are you disabling everything in the right side plugin panel or left install panel?

**Comment by Al12rs** [comment]
This should be fixed interest the Dev builds. If not it probably means that there are still some files from old skse installed that are incompatible with the newest version of the game. Create a new empty profile and make sure your data folder is completely vanilla (except for the skse files (not extensions or plugins) if you don't install them through a mod)
