### ISSUE TITLE
Add support for game Crusader Kings III

### ISSUE THREAD

**Issue by LonerEmperor** [ModOrganizer2/modorganizer#1889]
**This template is useful to add basic support using https://github.com/ModOrganizer2/modorganizer-basic_games.** 

**If you are vaguely familiar with programming you can try following the instructions on that link to get something working yourself. If you have trouble with that please fill in this template.**

**Please provide the following information for the game (remove the optional lines you do not use):**

- **Name:** Crusader Kings III
- **Short name:** crusaderkings3
- **Nexus ID [optional]:** crusaderkings3
- **Executable:** ck3.exe
- **Launcher [optional]:** dowser.exe
- **Data path:** \Steam\steamapps\common\Crusader Kings III
- **Documents path:** \Documents\Paradox Interactive\Crusader Kings III
- **Saves directory [optional]:** Path to the folder containing save games (this default to the path above).
- **Save extension [optional]:** Extension of the saves
- **Steam ID [optional]:** ID of the game on Steam (if the game is on Steam).

**Provide additional details regarding the game that could be required for the plugin.**

**Comment by AidanMaskelyne** [comment]
I've given it a shot, here's the repository for the new plugin if you would like to test it, as I am unable to myself. [My repo](https://github.com/AidanMaskelyne/modorganizer-basic_games)

**Comment by AidanMaskelyne** [comment]
Are you using the 2.5.0-RC version of Mod Organizer? I'd say give it a shot with the latest release candidate. Also, is ck3.exe in the root directory of the steam game folder (e.g. `Crusader Kings III\ck3.exe`)?

**Comment by AidanMaskelyne** [comment]
@LonerEmperor I've tweaked the plugin a bit, it should now work. Try downloading and extracting 2.5.0-RC, and just download [my plugin file](https://github.com/AidanMaskelyne/modorganizer-basic_games/blob/master/games/game_crusaderkings3.py) manually and put it in `plugins\basic_games\games` alongside all the other `game_xxx.py` files. Then launch MO2, creating a portable instance and it should detect your game.

**Comment by LonerEmperor** [comment]
I finally got MO2 to recognize CK3 as a supported game. Thanks for your effort. 

Now, the challenging part is adding mods. I tried adding my CK3 mods using MO2. MO2 would successfully launch the game but mods won't show in-game.

I also tried adding CK3 mods manually but still won't show in-game when launched from MO2.

**Comment by AidanMaskelyne** [comment]
If you just have a brief look inside the files, can you just verify the paths are correct? I had to go through multiple websites and may have copied something incorrectly. You'll only need to look at the stuff such as `GameDataPath = ....`

**Comment by LonerEmperor** [comment]
That's too technical for me. What do you mean? Where can I find that?

**Comment by AidanMaskelyne** [comment]
Here:
```
    GameDocumentsDirectory = "%DOCUMENTS%/Paradox Interactive/Crusader Kings III"
    GameDataPath = "%GAME_DOCUMENTS%/mod"
    GameSavesDirectory = "%GAME_DOCUMENTS%/save games"
    GameSaveExtension = "ck3"
```

Do these paths look about correct to you? The GameDataPath directory is where the mods go.

**Comment by LonerEmperor** [comment]
Yeah. The file locations are correct. However, one thing I've noticed is that MO2 doesn't place the .mod file directly in the GameDataPath.

I'm not sure if you're aware that mods in CK3 have 2 components:
1) The actual mod folder; and
2) The .mod text file for the same mod folder.

So inside the GameDataPath, "%GAME_DOCUMENTS%/mod" you should see:

[MOD_NAME]
[MOD_NAME.mod]

where

[MOD_NAME] is the mod's folder where all the mod files are, and
[MOD_NAME.mod] is a text file that makes the game see the mod and all other info about the mod.

But when a mod is installed using MO2, it only can install a folder where the mod files are but it doesn't install the .mod file directly into the GameDataPath.

I think this is the reason why CK3 mods become unavailable when launched from MO2.

**Comment by AidanMaskelyne** [comment]
Have you double checked that the files are correct in the mod in MO2?

**Comment by LonerEmperor** [comment]
Hi,

It's been a while. Been very busy with work that I didn't have time to play.

To answer your last question, "Have you double checked that the files are correct in the mod in MO2?"

Yes, I've checked that the mod files are correct in MO2 because all I need to do is install it (from the right side of MO2) and click the box so it will have a check in it to enable that mod (from the left side of MO2).

But as I mentioned before, if you install a CK3 mod manually, you should have 2 things in the GameDataPath, 

a folder [MOD_NAME] 
and 
a text file [MOD_NAME.mod]. 

These 2 are very important because, from what I've read, the text file ".mod" tells the game that the modifications/overrides/etc are inside the folder. Without the ".mod" file, the game can not see the mod folder.

Thanks.
