### ISSUE TITLE
Unable to compile scripts with CK

### ISSUE THREAD

**Issue by LostDragonist** [ModOrganizer2/modorganizer#709]
User report form somethingobscure#5444 on Discord

Hello.  Thanks for the new update!  I am having a problem creating new scripts in the Creation Kit (SSE) when run through MO2 version 2.2.0.  As soon as I enter the name of the script and hit Ok, I get a Papyrus error with an empty Compile Results.  Sometimes MO2 crashes at that point. (The CK does not.)   I am running MO2 as an admin, but not the CK.  The scripts should be getting sent to the overwrite folder, which has a folder structure for scripts, including a temp folder.  A source code file for the script is created (with an error inside), but no script.  mo_interface.log: https://pastebin.com/57wRxU4J  usvfs log: https://pastebin.com/57wRxU4J Windows version: https://i.imgur.com/Z0STKbf.png  This is what's in the error'd source code for the new script:  https://pastebin.com/e28fHxTH  I can confirm that the CK can create new scripts without issues when run outside of MO2.  I installed the update over the top of an existing installation.  I haven't touched or changed any configuration after doing so.

**Comment by LostDragonist** [comment]
User reports updating to Windows 10, Build 1809 did not affect the situation.  
Adding back the TEMP workaround to USVFS did not affect the situation.

**Comment by SomethingObscure** [comment]
I am available to help test possible fixes.

**Comment by TalenStorm** [comment]
First off, thanks so much for continuing to develop MO2, I can't use anything else to manage mods. :D

I am also experiencing this issue. The only difference is I am not running either program as admin. 

Happy to provide log files if needed.

Side note: The issue does not seem to occur when creating a script with the Fallout 4 Creation Kit through MO2. Not sure if this is relevant, but I thought it worth mentioning.

**Comment by ThisIsPatrick** [comment]
Also have this problem, Skyrim Legendary Edition.
Issue is the same as the first post describes.

Windows 10, Version 1709.
Mod Organizer 2.20beta9
Revision: 379c603

**Comment by npacker** [comment]
Same issue here, Skyrim LE.
I have found that the issue can develop after a short amount of time; I'll be able to compile a script or scripts successfully, then subsequent attempts will suddenly start failing as described in the OP.

Windows 10 Version 1809
Mod Organizer 2.2.0

**Comment by ozin370** [comment]
Getting this issue as well, on a Windows 7 install.
Compiling the scripts when running the CK outside of MO2.2 works

**Comment by xnyo** [comment]
Same issue here with Skyrim Special Edition and

Windows 10 Version 1809
Mod Organizer v2.2.0

The only workaround I've found is downgrading to Mod Organizer v2.1.6. I didn't test too much but I've tried creating a new quest with a quest script fragment and it compiled successfully.

**Comment by LostDragonist** [comment]
Got one report that this is fixed as of 2.2.2 - Alpha Build 17.4 (available on discord).

**Comment by SomethingObscure** [comment]
I just tested on 2.2.1 - Alpha Build 19, and I was able to create new scripts!  Thank you for the update!

**Comment by SomethingObscure** [comment]
I'm afraid that I spoke too soon. It's true that I'm now able to create new scripts without issue, but I'm not able to compile scripts in the editor.  I get a compile failed message and the console box is empty.

**Comment by SomethingObscure** [comment]
For what it's worth, I am able to compile scripts through Notepad++ running through MO2 (2.2.1rc2).  On very rare occasions it gives an error similar to the one the CK gives when it fails: That the file is in use by another process and can't be written to, but it only shows up once out of a hundred compiles and restarting Notepad++ fixes the issue.

**Comment by pcbeard** [comment]
I tried 2.2.1rc2 with Skyrim LE, and the issue is still unresolved for me. I'm using the stock PapyrusCompiler.exe installed by Steam. I create the .esp file and try to add a script to the Player actor.  The script file gets created in:

MO2-2.2.1-RC2\overwrite\Scripts\Source\PCBTest.psc

the contents of the script file after all this is:

Starting 1 compile threads for 1 files...
Compiling "PCBTest"...
C:\program files (x86)\steam\steamapps\common\Skyrim\Data\Scripts\Source\PCBTest.psc(0,0): error while attempting to read script PCBTest: The process cannot access the file 'C:\program files (x86)\steam\steamapps\common\Skyrim\Data\Scripts\Source\PCBTest.psc' because it is being used by another process.
No output generated for PCBTest, compilation failed.

Batch compile of 1 files finished. 0 succeeded, 1 failed.
Failed on PCBTest

**Comment by Jaiim** [comment]
This bug has started happening to me; I don't recall making any changes to my setup (unless I updated MO2 since the last time I was scripting and forgot about it), and I was previously able to compile scripts in the CK just fine, but all of a sudden, I started getting blank error boxes and then my scripts getting overwritten by compiler errors.  Just for information purposes I am on Windows 7 and using the SSE CK with CK Fixes (the error still occurs if I use the vanilla CK).  Here's an example of the error:

Starting 1 compile threads for 1 files...

Compiling "_jtestscript"...
F:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Source\Scripts\_jtestscript.psc(0,0): error while attempting to read script _jtestscript: The process cannot access the file 'F:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\Source\Scripts\_jtestscript.psc' because it is being used by another process.
No output generated for _jtestscript, compilation failed.

Batch compile of 1 files finished. 0 succeeded, 1 failed.
Failed on _jtestscript


This also happens when I attempt to add properties to scripts through the CK.  In an attempt to work around the issue, I closed the CK, edited the script in Notepad++ adding some properties to the script manually, then I loaded the CK again.  Attempting to then check the script properties will have an unusual behavior; the first time clicking the button, it does nothing.  The second time, it will pop an error box:  "Errors encountered while attempting to reload the script." and load the properties window without showing anything.  Trying to add a property will either pop a compiler error box with the error, or a blank box (seems to be inconsistent).  If the box shows the error, it WILL add the property to the script source, but the property window will still be blank.  If it's a blank box, your script will be overwritten by the same compiler error above.

I assumed this was some vfs error, so I updated MO2 to 2.2.1 (just released the other day), but the problem persists.

**Comment by isanae** [comment]
I've just released a patch for usvfs on #dev-builds on discord. My limited tests seem to be fine. Let me know if it fixes the problems.

**Comment by SomethingObscure** [comment]
Thank you, isanae.  I just tested the new dlls and was able to successfully compile a script using the CK through MO2v2.2.1!  I'll continue to test and report back if any problems come up!

**Comment by Jaiim** [comment]
I believe you've fixed it.  I am now able to save, compile, and add properties without a problem.

**Comment by npacker** [comment]
Compiling an existing script through the CK now works, awesome. 

There are still some minor lingering issues. For example, creating a brand new script through the interface still fails with the same error as before. The workaround is creating the new script file manually and triggering a compile through the interface.

In addition, it seems that adding new script properties through the interface also encounter the same error, again with the workaround of just adding them manually.

**Comment by agplayz** [comment]
> Compiling an existing script through the CK now works, awesome.
> 
> There are still some minor lingering issues. For example, creating a brand new script through the interface still fails with the same error as before. The workaround is creating the new script file manually and triggering a compile through the interface.
> 
> In addition, it seems that adding new script properties through the interface also encounter the same error, again with the workaround of just adding them manually.

I am having this same issue even after the update. I am trying to create a custom race but it's not allowing me to create the script and add properties. How do I do it manually as you say?

**Comment by npacker** [comment]
> I am having this same issue even after the update. I am trying to create a custom race but it's not allowing me to create the script and add properties. How do I do it manually as you say?

I would recommend installing an older version, such as 2.1.6, if you want to do scripting through MO2. It's just much less of a hassle.

**Comment by piotrmil** [comment]
I have the same issue. PLEASE fix this, I hate when stuff like that breaks my setup.

**Comment by isanae** [comment]
There's been a lot of confusion about usvfs and the CK recently, most of which is my fault. I released three patches for the CK since August. I'm not sure what the heck happened with the third one, but it did not contain the fixes that the second one had.

I've also done a piss-poor job at versioning this thing, making it difficult for everybody to understand what's going on.

So I'll try to be clear:

- The most recent official release of Mod Organizer is 2.2.1. It comes with usvfs 4.4.0. It has several problems with the CK, most of which are mentioned here.
- The most recent devbuild is 2.2.2 alpha 4 and it's available on discord. It comes with usvfs 4.4.4 which, to my knowledge, fixes all the issues with the CK.
- usvfs 4.4.4 is _also_ available as a standalone download. It is compatible with the official 2.2.1 release.

Here's the link to usvfs 4.4.4. Unzip it in your Mod Organizer installation folder. You might want to backup the original files in case of problems.

https://mega.nz/#!nYNijShb!lIEpEvU3CVCUQCLIznDkutsMdtW7qGe_JKGFNg5nXLA

If there are any remaining problems with the CK, add a comment here and we'll have a look.

**Comment by isanae** [comment]
I've had no reports of issues since this patch was released, so I'm closing this. It will be officially available in 2.2.2.

**Comment by piotrmil** [comment]
For the record, I downgraded to 2.1.6

**Comment by RashadDracula** [comment]
> User report form somethingobscure#5444 on Discord
> 
> Hello. Thanks for the new update! I am having a problem creating new scripts in the Creation Kit (SSE) when run through MO2 version 2.2.0. As soon as I enter the name of the script and hit Ok, I get a Papyrus error with an empty Compile Results. Sometimes MO2 crashes at that point. (The CK does not.) I am running MO2 as an admin, but not the CK. The scripts should be getting sent to the overwrite folder, which has a folder structure for scripts, including a temp folder. A source code file for the script is created (with an error inside), but no script. mo_interface.log: https://pastebin.com/57wRxU4J usvfs log: https://pastebin.com/57wRxU4J Windows version: https://i.imgur.com/Z0STKbf.png This is what's in the error'd source code for the new script: https://pastebin.com/e28fHxTH I can confirm that the CK can create new scripts without issues when run outside of MO2. I installed the update over the top of an existing installation. I haven't touched or changed any configuration after doing so.

Try using the **[Unofficial Creation Kit Patch](https://www.nexusmods.com/skyrimspecialedition/mods/41195?tab=description)** and see if the Issue is fixed.

it also fixes Many other issues and also Provides Speed Improvements
